ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'NURTURING';
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "nextContactDate" TIMESTAMP(3);
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "nurtureReason" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "nurtureNotes" TEXT;
